name: pangeo
channels:
 - conda-forge
 - nodefaults
dependencies:
 - adlfs
 - black # req for code_formatter ext
 - boto3
 - bottleneck
 - bqplot
 - cartopy
 - cfgrib
 - ciso
 - dask
 - dask-gateway
 - dask-ml
 - datashader
 - descartes
 - distributed
 - docker-py
 - earthaccess
 - eofs
 - erddapy
 - esmpy
 - fastjmd95
 - flox
 - fsspec
 - gcm_filters
 - geocube
 - geopandas
 - geopy
 - geoviews-core
 - gh
 - gh-scoped-creds
 - git-lfs
 - gsw
 - h5netcdf
 - h5py
 - hera
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipykernel>=6.21.2
 - ipyleaflet
 - ipyleaflet
 - ipympl
 - ipytree
 - ipywidgets
 - isort # req for code_formatter ext
 - jupyter-lsp
 - jupyter-panel-proxy
 - jupyter-resource-usage
 - jupyter-server-proxy
 - jupyterhub-base
 - jupyterhub-singleuser
 - jupyterlab
 - jupyterlab_code_formatter
 - jupyterlab_execute_time
 - jupyterlab_iframe
 - jupyterlab_templates
 - jupyterlab-geojson
 - jupyterlab-git
 - kerchunk
 - lfortran
 - lxml
 - lz4
 - matplotlib-base
 - metpy
 - minio
 - nb_conda_kernels
 - nbstripout
 - nc-time-axis
 - netcdf4
 - numcodecs
 - numpy
 - odc-algo
 - odc-cloud[ASYNC]
 - odc-io
 - odc-stac
 - odc-stats
 - pandas
 - panel
 - param
 - parcels
 - planetary-computer
 - pop-tools
 - pyarrow
 - pycamhd
 - pydap
 - pygeos
 - pymannkendall
 - pystac
 - pystac-client
 - python-blosc
 - python-gist
 - python-graphviz
 - python-lsp-server 
 - r-irkernel
 - r-languageserver
 - rasterio
 - rechunker
 - rio-cogeo
 - rioxarray
 - s2cloudless
 - s3fs
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - seaborn
 - snakeviz
 - sparse
 - spyndex
 - stackstac
 - tiledb-py
 - timezonefinder
 - xarray
 - xarray_leaflet
 - xarray-datatree
 - xarray-spatial
 - xarrayutils
 - xbatcher
 - xcape
 - xclim
 - xesmf
 - xgcm
 - xhistogram
 - xmip
 - xmitgcm
 - xpublish
 - xrft
 - xskillscore
 - zarr
 # - geogif
 # - xcube>=0.9.1
# - rise